# tools/embed_customisation.py <output.cpp> [<customisation directory>]
#
# Turns a customisation - linestyle and symbol libraries, survey code files -
# into a C++ source file, so the linestyles, symbols and survey codes are part
# of the program and not something it has to be given.
#
# Run by CMake at build time, on the directory KATANA_CUSTOMISATION_DIR names
# (resources/customisation/ by default). The customisation itself is
# third-party material under its own licence and is NOT in this repository
# (see .gitignore), so a checkout without it generates an EMPTY table and
# Katana draws every line as the plain continuous line. The generated file is
# written into the build directory and is never committed.
#
# The files are embedded in name order, which is the order they are read in:
# that is what puts survey_codes.mapfile ahead of survey_codes_names.mapfile,
# and the first survey code file wins a field both give.
#
# The bytes are embedded as they were read and parsed once, lazily, on first
# use - rather than generating C++ that builds the 792 definitions and 35,000
# strokes directly. Two reasons: the parser is the same one a loaded file goes
# through, so there is one reader and no second way for the two to disagree;
# and 35,000 brace-initialised structs is a multi-megabyte translation unit
# that costs more to compile than the parse costs to run.
import io
import os
import sys


def read(path):
    raw = io.open(path, 'rb').read()
    return raw


def looks_like_customisation(raw):
    text = raw.decode('utf-16' if raw[:2] in (b'\xff\xfe', b'\xfe\xff') else 'utf-8', 'replace')
    if '<map_file' in text:
        return True
    return any(word in text for word in ('worldstyle', 'paperstyle', 'twoptstyle'))


def cpp_string(text):
    # A C++ string literal of the UTF-8 bytes of `text`. Every byte that is not
    # plainly safe becomes a THREE-digit octal escape: octal rather than hex
    # because a hex escape runs on through any hex digit after it, and always
    # three digits because an octal escape stops after three.
    out = []
    for byte in text.encode('utf-8'):
        char = chr(byte)
        if char.isascii() and (char.isalnum() or char in ' ._-()'):
            out.append(char)
        else:
            out.append('\\%03o' % byte)
    return '"' + ''.join(out) + '"'


def emit(out, files):
    out.write('// GENERATED by tools/embed_customisation.py - do not edit, do not commit.\n')
    out.write('//\n')
    out.write('// The built-in customisation compiled into this build: its linestyle and\n')
    out.write('// symbol definitions and its survey code rules. See the script for why the\n')
    out.write('// bytes are embedded and parsed once rather than generated as C++ structures.\n\n')
    out.write('#include "builtin_customisation.hpp"\n\n')
    out.write('namespace katana::archive12d::detail {\n\n')
    out.write('namespace {\n\n')

    for index, (name, raw) in enumerate(files):
        # The name escaped even in the comment: one ending in a backslash
        # would otherwise continue the comment over the declaration below it.
        out.write('// %s, %d bytes\n' % (cpp_string(name), len(raw)))
        out.write('constexpr unsigned char kFile%d[] = {' % index)
        for at, byte in enumerate(raw):
            if at % 20 == 0:
                out.write('\n    ')
            out.write('%d,' % byte)
        out.write('\n};\n\n')

    out.write('} // namespace\n\n')
    # The NAME goes with the bytes: it is what the definitions read from each
    # file are stamped with (LineStyle::source), and a built-in definition
    # must say where it came from exactly as a loaded one does.
    out.write('std::vector<EmbeddedFile> builtinCustomisationFiles()\n{\n')
    if not files:
        out.write('    return {};\n')
    else:
        out.write('    return {\n')
        for index, (name, raw) in enumerate(files):
            out.write('        EmbeddedFile{std::string_view(%s, %d),\n'
                      % (cpp_string(name), len(name.encode('utf-8'))))
            out.write('                     std::string_view(reinterpret_cast<const char*>(kFile%d), %d)},\n'
                      % (index, len(raw)))
        out.write('    };\n')
    out.write('}\n\n')
    out.write('} // namespace katana::archive12d::detail\n')


def main():
    if len(sys.argv) < 2:
        sys.exit('usage: embed_customisation.py <output.cpp> [<directory>]')
    output = sys.argv[1]
    directory = sys.argv[2] if len(sys.argv) > 2 else None

    files = []
    if directory and os.path.isdir(directory):
        for name in sorted(os.listdir(directory)):
            path = os.path.join(directory, name)
            if not os.path.isfile(path):
                continue
            raw = read(path)
            if looks_like_customisation(raw):
                files.append((name, raw))

    os.makedirs(os.path.dirname(output) or '.', exist_ok=True)
    with io.open(output, 'w', encoding='utf-8', newline='\n') as out:
        emit(out, files)
    total = sum(len(raw) for _, raw in files)
    print('embedded %d customisation files, %d bytes' % (len(files), total))


if __name__ == '__main__':
    main()
