#!/usr/bin/env python3
"""Writes src/katana_ifc/product_classes.inc: every entity that descends from
IfcProduct in the IFC schemas the IFC import reads (IFC2X3, IFC4, IFC4X3_ADD2),
in the schemas' own spelling, with what the import does with it.

The import needs the list because an ISO 10303-21 file names its entities in
upper case and carries no schema: without it, a product cannot be told from
any other instance, nor reported as "IfcPipeSegment" rather than
"IFCPIPESEGMENT". The list is the schemas', read through IfcOpenShell
(pip install ifcopenshell); the file is committed, and this regenerates it:

    python tools/ifc_product_classes.py > src/katana_ifc/product_classes.inc

Developer tool only (Rule 1): nothing runs it at build or run time.
"""

import ifcopenshell

SCHEMAS = ["IFC2X3", "IFC4", "IFC4X3_ADD2"]


def descendants(schema, name):
    out = set()
    stack = [schema.declaration_by_name(name)]
    while stack:
        entity = stack.pop()
        out.add(entity.name())
        stack.extend(entity.subtypes())
    return out


def main():
    kinds = {}
    for schema_name in SCHEMAS:
        schema = ifcopenshell.ifcopenshell_wrapper.schema_by_name(schema_name)
        products = descendants(schema, "IfcProduct")
        spatial = set()
        for root in ("IfcSpatialStructureElement", "IfcSpatialElement"):
            try:
                spatial |= descendants(schema, root)
            except RuntimeError:
                pass
        positioning = set()
        # IfcLinearElement: the layouts and segments of an alignment, read as
        # part of it rather than drawn on their own.
        for root in ("IfcPositioningElement", "IfcLinearPositioningElement", "IfcGrid",
                     "IfcLinearElement"):
            try:
                positioning |= descendants(schema, root)
            except RuntimeError:
                pass
        features = set()
        for root in ("IfcFeatureElementSubtraction", "IfcVirtualElement", "IfcPort"):
            try:
                features |= descendants(schema, root)
            except RuntimeError:
                pass
        for name in products:
            if name in spatial:
                kind = "Spatial"
            elif name in positioning:
                kind = "Positioning"
            elif name in features:
                kind = "NotDrawn"
            else:
                kind = "Drawn"
            kinds.setdefault(name, kind)
    print("// Generated by tools/ifc_product_classes.py from IfcOpenShell "
          f"{ifcopenshell.version}'s {', '.join(SCHEMAS)}; do not edit.")
    for name in sorted(kinds, key=str.upper):
        print(f'{{"{name.upper()}", "{name}", ProductKind::{kinds[name]}}},')


if __name__ == "__main__":
    main()
