#!/usr/bin/env python3
"""Writes src/katana_ifc/product_classes.inc: every entity that descends from
IfcProduct in the IFC schemas the IFC import reads (IFC2X3, IFC4, IFC4X3_ADD2),
in the schemas' own spelling, with what the import does with it.

The import needs the list because an ISO 10303-21 file names its entities in
upper case and carries no schema: without it, a product cannot be told from
any other instance, nor reported as "IfcPipeSegment" rather than
"IFCPIPESEGMENT". The list is the schemas', read through IfcOpenShell
(pip install ifcopenshell); the file is committed, and this regenerates it:

    python tools/ifc_product_classes.py > src/katana_ifc/product_classes.inc

With --predefined it writes src/katana_ifc/predefined_types.inc instead: every
IFC4X3_ADD2 entity whose PredefinedType is an enumeration, with the
enumeration's values - what a project's classification rules are checked
against, so that a rule naming a value the schema does not have is refused
when its file is read rather than written into an invalid file:

    python tools/ifc_product_classes.py --predefined > src/katana_ifc/predefined_types.inc

Developer tool only (Rule 1): nothing runs it at build or run time.
"""

import sys

import ifcopenshell

SCHEMAS = ["IFC2X3", "IFC4", "IFC4X3_ADD2"]


def descendants(schema, name):
    out = set()
    stack = [schema.declaration_by_name(name)]
    while stack:
        entity = stack.pop()
        out.add(entity.name())
        stack.extend(entity.subtypes())
    return out


def main():
    kinds = {}
    for schema_name in SCHEMAS:
        schema = ifcopenshell.ifcopenshell_wrapper.schema_by_name(schema_name)
        products = descendants(schema, "IfcProduct")
        spatial = set()
        for root in ("IfcSpatialStructureElement", "IfcSpatialElement"):
            try:
                spatial |= descendants(schema, root)
            except RuntimeError:
                pass
        positioning = set()
        # IfcLinearElement: the layouts and segments of an alignment, read as
        # part of it rather than drawn on their own.
        for root in ("IfcPositioningElement", "IfcLinearPositioningElement", "IfcGrid",
                     "IfcLinearElement"):
            try:
                positioning |= descendants(schema, root)
            except RuntimeError:
                pass
        features = set()
        for root in ("IfcFeatureElementSubtraction", "IfcVirtualElement", "IfcPort"):
            try:
                features |= descendants(schema, root)
            except RuntimeError:
                pass
        for name in products:
            if name in spatial:
                kind = "Spatial"
            elif name in positioning:
                kind = "Positioning"
            elif name in features:
                kind = "NotDrawn"
            else:
                kind = "Drawn"
            kinds.setdefault(name, kind)
    print("// Generated by tools/ifc_product_classes.py from IfcOpenShell "
          f"{ifcopenshell.version}'s {', '.join(SCHEMAS)}; do not edit.")
    for name in sorted(kinds, key=str.upper):
        print(f'{{"{name.upper()}", "{name}", ProductKind::{kinds[name]}}},')


def predefined():
    schema = ifcopenshell.ifcopenshell_wrapper.schema_by_name("IFC4X3_ADD2")
    rows = {}
    for declaration in schema.declarations():
        entity = declaration.as_entity()
        if entity is None:
            continue
        for attribute in entity.all_attributes():
            if attribute.name() != "PredefinedType":
                continue
            declared = attribute.type_of_attribute()
            while hasattr(declared, "declared_type"):
                declared = declared.declared_type()
            if hasattr(declared, "enumeration_items"):
                rows[entity.name()] = " ".join(declared.enumeration_items())
    print("// Generated by tools/ifc_product_classes.py --predefined from IfcOpenShell "
          f"{ifcopenshell.version}'s IFC4X3_ADD2; do not edit.")
    for name in sorted(rows, key=str.upper):
        print(f'{{"{name}", "{rows[name]}"}},')


if __name__ == "__main__":
    predefined() if "--predefined" in sys.argv[1:] else main()
